[project]
name = "manage_last_admin"
dynamic = ["version"]

[build-system]
requires = ["setuptools", "setuptools_scm", "wheel"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
known_first_party = [
    "manage_last_admin",
    "tests"
]
